alloy:
  extraArgs:
    - --stability.level=experimental
  extraEnv:
    - name: LOKI_PASSWORD
      valueFrom:
        secretKeyRef:
          name: grafana-cloud-keys
          key: loki-key
    - name: LOKI_USERNAME
      valueFrom:
        secretKeyRef:
          name: grafana-cloud-keys
          key: loki-username
    - name: MIMIR_PASSWORD
      valueFrom:
        secretKeyRef:
          name: grafana-cloud-keys
          key: mimir-key
    - name: MIMIR_USERNAME
      valueFrom:
        secretKeyRef:
          name: grafana-cloud-keys
          key: mimir-username
  mounts:
    varlog: true
