kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
  - role: worker
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30001
  - role: worker
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30002
