alloy:
  clustering:
    enabled: true
  extraPorts:
   - name: "otlp"
     port: 4317
     targetPort: 4317
     protocol: "TCP"
  extraArgs:
    - --stability.level=experimental
  extraEnv:
    - name: OTLP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: grafana-cloud-keys
          key: otlp-key
    - name: OTLP_USERNAME
      valueFrom:
        secretKeyRef:
          name: grafana-cloud-keys
          key: otlp-username
controller:
  type: 'statefulset'
  replicas: 3
