---
apiVersion: v1
kind: Namespace
metadata:
  name: telemetrygen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetrygen-deployment
  namespace: telemetrygen
spec:
  replicas: 3
  selector:
    matchLabels:
      app: telemetrygen
  template:
    metadata:
      labels:
        app: telemetrygen
    spec:
      containers:
        - name: telemetrygen-traces
          image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
          args:
            - "traces"
            - "--otlp-endpoint=alloy-sts-cluster.alloy.svc.cluster.local:4317"
            - "--otlp-insecure"
            - "--interval=10s"
            - "--rate=0.1"
            - "--duration=10h"
#        - name: telemetrygen-logs
#          image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
#          args:
#            - "logs"
#            - "--otlp-endpoint=alloy-sts-cluster.alloy.svc.cluster.local:4317"
#            - "--otlp-insecure"
#            - "--interval=10s"
#            - "--rate=0.1"
#            - "--duration=10h"
#        - name: telemetrygen-metrics
#          image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
#          args:
#            - "metrics"
#            - "--otlp-endpoint=alloy-sts-cluster.alloy.svc.cluster.local:4317"
#            - "--otlp-insecure"
#            - "--interval=10s"
#            - "--rate=0.1"
#            - "--duration=10h"
